from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)


author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'cheap_talk_survey'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):

    gender = models.IntegerField(
        choices=[
            [0, 'Male'],
            [1, 'Female'],
            [2, 'Other'],
        ],
        widget=widgets.RadioSelect)

    age = models.IntegerField()

    nationality = models.StringField(
        choices=[
            ['Afghanistan', 'Afghanistan'],
            ['Albania', 'Albania'],
            ['Algeria', 'Algeria'],
            ['Andorra', 'Andorra'],
            ['Angola', 'Angola'],
            ['Antigua and Barbuda', 'Antigua and Barbuda'],
            ['Argentina', 'Argentina'],
            ['Armenia', 'Armenia'],
            ['Australia', 'Australia'],
            ['Austria', 'Austria'],
            ['Azerbaijan', 'Azerbaijan'],
            ['The Bahamas', 'The Bahamas'],
            ['Bahrain', 'Bahrain'],
            ['Bangladesh', 'Bangladesh'],
            ['Barbados', 'Barbados'],
            ['Belarus', 'Belarus'],
            ['Belgium', 'Belgium'],
            ['Belize', 'Belize'],
            ['Benin', 'Benin'],
            ['Bhutan', 'Bhutan'],
            ['Bolivia', 'Bolivia'],
            ['Bosnia and Herzegovina', 'Bosnia and Herzegovina'],
            ['Botswana', 'Botswana'],
            ['Brazil', 'Brazil'],
            ['Brunei', 'Brunei'],
            ['Bulgaria', 'Bulgaria'],
            ['Burkina Faso', 'Burkina Faso'],
            ['Burundi', 'Burundi'],
            ['Cabo Verde', 'Cabo Verde'],
            ['Cambodia', 'Cambodia'],
            ['Cameroon', 'Cameroon'],
            ['Canada', 'Canada'],
            ['Central African Republic', 'Central African Republic'],
            ['Chad', 'Chad'],
            ['Chile', 'Chile'],
            ['China', 'China'],
            ['Colombia', 'Colombia'],
            ['Comoros', 'Comoros'],
            ['Congo, Democratic Republic of the', 'Congo, Democratic Republic of the'],
            ['Congo, Republic of the', 'Congo, Republic of the'],
            ['Costa Rica', 'Costa Rica'],
            ['Côte d’Ivoire', 'Côte d’Ivoire'],
            ['Croatia', 'Croatia'],
            ['Cuba', 'Cuba'],
            ['Cyprus', 'Cyprus'],
            ['Czech Republic', 'Czech Republic'],
            ['Denmark', 'Denmark'],
            ['Djibouti', 'Djibouti'],
            ['Dominica', 'Dominica'],
            ['Dominican Republic', 'Dominican Republic'],
            ['East Timor (Timor-Leste)', 'East Timor (Timor-Leste)'],
            ['Ecuador', 'Ecuador'],
            ['Egypt', 'Egypt'],
            ['El Salvador', 'El Salvador'],
            ['Equatorial Guinea', 'Equatorial Guinea'],
            ['Eritrea', 'Eritrea'],
            ['Estonia', 'Estonia'],
            ['Ethiopia', 'Ethiopia'],
            ['Fiji', 'Fiji'],
            ['Finland', 'Finland'],
            ['France', 'France'],
            ['Gabon', 'Gabon'],
            ['The Gambia', 'The Gambia'],
            ['Georgia', 'Georgia'],
            ['Germany', 'Germany'],
            ['Ghana', 'Ghana'],
            ['Greece', 'Greece'],
            ['Grenada', 'Grenada'],
            ['Guatemala', 'Guatemala'],
            ['Guinea', 'Guinea'],
            ['Guinea-Bissau', 'Guinea-Bissau'],
            ['Guyana', 'Guyana'],
            ['Haiti', 'Haiti'],
            ['Honduras', 'Honduras'],
            ['Hungary', 'Hungary'],
            ['Iceland', 'Iceland'],
            ['India', 'India'],
            ['Indonesia', 'Indonesia'],
            ['Iran', 'Iran'],
            ['Iraq', 'Iraq'],
            ['Ireland', 'Ireland'],
            ['Israel', 'Israel'],
            ['Italy', 'Italy'],
            ['Jamaica', 'Jamaica'],
            ['Japan', 'Japan'],
            ['Jordan', 'Jordan'],
            ['Kazakhstan', 'Kazakhstan'],
            ['Kenya', 'Kenya'],
            ['Kiribati', 'Kiribati'],
            ['Korea, North', 'Korea, North'],
            ['Korea, South', 'Korea, South'],
            ['Kosovo', 'Kosovo'],
            ['Kuwait', 'Kuwait'],
            ['Kyrgyzstan', 'Kyrgyzstan'],
            ['Laos', 'Laos'],
            ['Latvia', 'Latvia'],
            ['Lebanon', 'Lebanon'],
            ['Lesotho', 'Lesotho'],
            ['Liberia', 'Liberia'],
            ['Libya', 'Libya'],
            ['Liechtenstein', 'Liechtenstein'],
            ['Lithuania', 'Lithuania'],
            ['Luxembourg', 'Luxembourg'],
            ['Macedonia', 'Macedonia'],
            ['Madagascar', 'Madagascar'],
            ['Malawi', 'Malawi'],
            ['Malaysia', 'Malaysia'],
            ['Maldives', 'Maldives'],
            ['Mali', 'Mali'],
            ['Malta', 'Malta'],
            ['Marshall Islands', 'Marshall Islands'],
            ['Mauritania', 'Mauritania'],
            ['Mauritius', 'Mauritius'],
            ['Mexico', 'Mexico'],
            ['Micronesia, Federated States of', 'Micronesia, Federated States of'],
            ['Moldova', 'Moldova'],
            ['Monaco', 'Monaco'],
            ['Mongolia', 'Mongolia'],
            ['Montenegro', 'Montenegro'],
            ['Morocco', 'Morocco'],
            ['Mozambique', 'Mozambique'],
            ['Myanmar (Burma)', 'Myanmar (Burma)'],
            ['Namibia', 'Namibia'],
            ['Nauru', 'Nauru'],
            ['Nepal', 'Nepal'],
            ['Netherlands', 'Netherlands'],
            ['New Zealand', 'New Zealand'],
            ['Nicaragua', 'Nicaragua'],
            ['Niger', 'Niger'],
            ['Nigeria', 'Nigeria'],
            ['Norway', 'Norway'],
            ['Oman', 'Oman'],
            ['Pakistan', 'Pakistan'],
            ['Palau', 'Palau'],
            ['Panama', 'Panama'],
            ['Papua New Guinea', 'Papua New Guinea'],
            ['Paraguay', 'Paraguay'],
            ['Peru', 'Peru'],
            ['Philippines', 'Philippines'],
            ['Poland', 'Poland'],
            ['Portugal', 'Portugal'],
            ['Qatar', 'Qatar'],
            ['Romania', 'Romania'],
            ['Russia', 'Russia'],
            ['Rwanda', 'Rwanda'],
            ['Saint Kitts and Nevis', 'Saint Kitts and Nevis'],
            ['Saint Lucia', 'Saint Lucia'],
            ['Saint Vincent and the Grenadines', 'Saint Vincent and the Grenadines'],
            ['Samoa', 'Samoa'],
            ['San Marino', 'San Marino'],
            ['Sao Tome and Principe', 'Sao Tome and Principe'],
            ['Saudi Arabia', 'Saudi Arabia'],
            ['Senegal', 'Senegal'],
            ['Serbia', 'Serbia'],
            ['Seychelles', 'Seychelles'],
            ['Sierra Leone', 'Sierra Leone'],
            ['Singapore', 'Singapore'],
            ['Slovakia', 'Slovakia'],
            ['Slovenia', 'Slovenia'],
            ['Solomon Islands', 'Solomon Islands'],
            ['Somalia', 'Somalia'],
            ['South Africa', 'South Africa'],
            ['Spain', 'Spain'],
            ['Sri Lanka', 'Sri Lanka'],
            ['Sudan', 'Sudan'],
            ['Sudan, South', 'Sudan, South'],
            ['Suriname', 'Suriname'],
            ['Swaziland', 'Swaziland'],
            ['Sweden', 'Sweden'],
            ['Switzerland', 'Switzerland'],
            ['Syria', 'Syria'],
            ['Taiwan', 'Taiwan'],
            ['Tajikistan', 'Tajikistan'],
            ['Tanzania', 'Tanzania'],
            ['Thailand', 'Thailand'],
            ['Togo', 'Togo'],
            ['Tonga', 'Tonga'],
            ['Trinidad and Tobago', 'Trinidad and Tobago'],
            ['Tunisia', 'Tunisia'],
            ['Turkey', 'Turkey'],
            ['Turkmenistan', 'Turkmenistan'],
            ['Tuvalu', 'Tuvalu'],
            ['Uganda', 'Uganda'],
            ['Ukraine', 'Ukraine'],
            ['United Arab Emirates', 'United Arab Emirates'],
            ['United Kingdom', 'United Kingdom'],
            ['United States (USA)', 'United States (USA)'],
            ['Uruguay', 'Uruguay'],
            ['Uzbekistan', 'Uzbekistan'],
            ['Vanuatu', 'Vanuatu'],
            ['Vatican City', 'Vatican City'],
            ['Venezuela', 'Venezuela'],
            ['Vietnam', 'Vietnam'],
            ['Yemen', 'Yemen'],
            ['Zambia', 'Zambia'],
            ['Zimbabwe', 'Zimbabwe'],
        ],
        )

    income = models.IntegerField(
        choices=[
            [0, 'Less than $10,000'],
            [1, '$10,000 to $19,999'],
            [2, '$20,000 to $29,999'],
            [3, '$30,000 to $39,999'],
            [4, '$40,000 to $49,999'],
            [5, '$50,000 to $59,999'],
            [6, '$60,000 to $69,999'],
            [7, '$70,000 to $79,999'],
            [8, '$80,000 to $89,999'],
            [9, '$90,000 to $99,999'],
            [10, '$100,000 to $149,999'],
            [11, '$150,000 or more'],
        ],
        widget=widgets.RadioSelect)

    education = models.IntegerField(
        choices=[
            [0, 'Less than a high school diploma'],
            [1, 'High school degree or equivalent (e.g. GED)'],
            [2, 'Some college, no degree'],
            [3, 'Associate degree (e.g. AA, AS)'],
            [4, 'Bachelor’s degree (e.g. BA, BS)'],
            [5, 'Master’s degree (e.g. MA, MS, MEd)'],
            [6, 'Professional degree (e.g. MD, DDS, DVM)'],
            [7, 'Doctorate (e.g. PhD, EdD)'],
        ],
        widget=widgets.RadioSelect)

    riskaversion = models.IntegerField(
        choices=[
            [0, '0'],
            [1, '1'],
            [2, '2'],
            [3, '3'],
            [4, '4'],
            [5, '5'],
            [6, '6'],
            [7, '7'],
            [8, '8'],
            [9, '9'],
            [10, '10'],
        ],
        widget=widgets.RadioSelectHorizontal)


    pass
